apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Demo-System
  description: This is a demo System
spec:
  owner: Demo-Team
  domain: logistics
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-service-1
  title: BackEnd API 
  description: This is a test API . 
  
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - lambda
    - dotnetcore
spec:
  type: website
  lifecycle: production
  owner: Demo-Team
  system: Demo-System 
  dependsOn: ['Component:backend-function-1']

